### ISSUE TITLE
workflow for maxdocs doesn't do what's intdended

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/actions#1]
apropos https://github.com/flucoma/flucoma-docs/issues/39 

From what I can make out, this checking out the `flucoma-max` repo, downloading docs separately, but then not pointing the flucoma-max to the downloaded docs, so it ends up doing it again via `FetchContent` (in which case it gets `main` not `dev`). 

https://github.com/flucoma/actions/blob/bf8d4d9b75f99869ae0a73b93f073e50b16d756c/maxdocs/action.yaml#L11-L26

We shouldn't need to checkout `flucoma-max` if you're just building the docs here. The steps should be: 
* checkout flucoma-docs/dev (when `dev is the branch of interest) 
* * configure *that* (which will still involve grabbing core and its dependencies 😢 ) 

In shellish, I think that ought to pan out as

```
git clone --branch ${{ inputs.branch }} https://github.com/flucoma/flucoma-docs.git docs
cd docs
cmake -B build -GNinja
cmake --build build --target MAKE_MAX_REF
```

Presumably this goes for the other docs workflows too. (in which case there's scope for reducing to a single workflow that just takes 2 variables, git ref and target)

**Comment by jamesb93** [comment]
This is all good positive change. Feel free to attack as you see fit. The only thing that is monstrous is that the actions refer to a tagged commit so we need to update where the v4 tag is or make a v5 that works (it's currently underway for other stuff which may be paused for now)
